import { Request, Response } from 'express';
import bcrypt from 'bcryptjs';
import { v4 as uuidv4 } from 'uuid';
import * as azureTableService from '../services/azureTableService.js';
import * as azureBlobService from '../services/azureBlobService.js';
import * as gcNotifyService from '../services/gcNotifyService.js';
import * as assemblylineService from '../services/assemblylineService.js';

const FRONTEND_URL = process.env.FRONTEND_URL || 'http://localhost:5173';

export const createRequest = async (req: Request, res: Response) => {
    try {
        const { uploaderEmail, requestedFileTypes, expirationDays, allowMultiple, caseNumber } = req.body;
        let requestorEmail = req.user?.preferred_username || req.body.requestorEmail || 'admin@example.com';
        
        // Remove characters forbidden in Azure Table keys: / \ # ? 
        requestorEmail = requestorEmail.replace(/[\/\\#\?]/g, '_');

        if (!uploaderEmail) {
            return res.status(400).json({ error: 'uploaderEmail required' });
        }

        // Auto-generate 18-character secret for uploader
        const autoGeneratedSecret = generateUploaderSecret();
        const secretHash = await bcrypt.hash(autoGeneratedSecret, 10);

        const entity = await azureTableService.createUploadRequest(
            requestorEmail, 
            uploaderEmail, 
            requestedFileTypes || 'pdf,xlsx',
            secretHash,
            parseInt(expirationDays as string, 10) || 7,
            allowMultiple === true,
            caseNumber
        );
        
        const uploadLink = `${FRONTEND_URL}/upload/${entity.rowKey}`;
        
        // Send email with auto-generated secret
        await gcNotifyService.sendUploadRequestEmail(
            uploaderEmail,
            requestorEmail,
            uploadLink,
            autoGeneratedSecret,
            allowMultiple === true,
            entity.requestNumber,
            entity.caseNumber
        );

        res.status(201).json({
            message: 'Upload request created.',
            token: entity.rowKey,
            requestNumber: entity.requestNumber,
            caseNumber: entity.caseNumber,
            request: entity
        });
    } catch (error: any) {
        console.error('Error creating request:', error.message, error.stack);
        res.status(500).json({ error: 'Internal server error', details: error.message });
    }
};

export const getRequestInfo = async (req: Request, res: Response) => {
    try {
        const token = req.params.token as string;
        const request = await azureTableService.getRequestByTokenOnly(token);
        
        if (!request || (request.expiresAt && new Date(request.expiresAt) < new Date())) {
            return res.status(404).json({ error: 'Upload request not found or expired.' });
        }

        res.json({
            uploaderEmail: request.uploaderEmail,
            requestedFileTypes: request.requestedFileTypes,
            status: request.status,
            requiresSecret: !!request.secretHash,
            blobUri: request.blobUri || null,
            allowMultiple: request.allowMultiple || false,
            isClosed: request.isClosed || false,
            requestNumber: request.requestNumber,
            caseNumber: request.caseNumber
        });
    } catch (error) {
        res.status(500).json({ error: 'Internal server error' });
    }
};

export const validateSecret = async (req: Request, res: Response) => {
    try {
        const token = req.params.token as string;
        const { secret } = req.body;
        const request = await azureTableService.getRequestByTokenOnly(token);
        
        if (!request || (request.expiresAt && new Date(request.expiresAt) < new Date())) {
            return res.status(404).json({ error: 'Not found or expired' });
        }
        
        if (request.secretHash) {
            if (!secret) return res.status(401).json({ error: 'Secret required' });
            const isValid = await bcrypt.compare(secret, request.secretHash);
            if (!isValid) return res.status(401).json({ error: 'Invalid secret' });
        }
        
        res.json({ success: true });
    } catch (error) {
        res.status(500).json({ error: 'Internal server error' });
    }
};

const parseAllowedExtensions = (requestedFileTypes?: string): string[] => {
    if (!requestedFileTypes) return [];
    return requestedFileTypes
        .split(',')
        .map(ext => ext.trim().toLowerCase().replace(/^\./, ''))
        .filter(Boolean);
};

const isExtensionAllowed = (filename: string, allowedExtensions: string[]): boolean => {
    const ext = filename.split('.').pop()?.toLowerCase();
    return !!ext && allowedExtensions.includes(ext);
};

export const generateUploadSas = async (req: Request, res: Response) => {
    try {
        const token = req.params.token as string;
        const { filename, secret } = req.body;

        const request = await azureTableService.getRequestByTokenOnly(token);
        
        if (!request || (request.expiresAt && new Date(request.expiresAt) < new Date())) {
            return res.status(404).json({ error: 'Not found or expired' });
        }
        // Validate secret
        if (request.secretHash) {
            if (!secret) return res.status(401).json({ error: 'Secret required' });
            const isValid = await bcrypt.compare(secret, request.secretHash);
            if (!isValid) return res.status(401).json({ error: 'Invalid secret' });
        }

        const allowedExtensions = parseAllowedExtensions(request.requestedFileTypes);
        if (!filename || typeof filename !== 'string') {
            return res.status(400).json({ error: 'Filename required' });
        }

        const normalizedFilename = filename.toString();
        const ext = normalizedFilename.split('.').pop()?.toLowerCase();
        if (!ext || (allowedExtensions.length > 0 && !isExtensionAllowed(normalizedFilename, allowedExtensions))) {
            return res.status(400).json({ error: `Invalid file type. Allowed types: ${request.requestedFileTypes}` });
        }

        const blobName = `${token}-${Date.now()}.${ext}`;

        const sasInfo = azureBlobService.generateUploadSasToken(blobName);
        res.json(sasInfo);
    } catch (error) {
        res.status(500).json({ error: 'Internal server error' });
    }
};

export const confirmUpload = async (req: Request, res: Response) => {
    try {
        const token = req.params.token as string;
        const { blobName } = req.body;

        const request = await azureTableService.getRequestByTokenOnly(token);
        if (!request) return res.status(404).json({ error: 'Not found' });

        const allowedExtensions = parseAllowedExtensions(request.requestedFileTypes);
        if (!blobName || typeof blobName !== 'string') {
            return res.status(400).json({ error: 'blobName required' });
        }

        const extension = blobName.split('.').pop()?.toLowerCase();
        if (!extension || (allowedExtensions.length > 0 && !isExtensionAllowed(blobName, allowedExtensions))) {
            return res.status(400).json({ error: `File type not permitted. Allowed types: ${request.requestedFileTypes}` });
        }

        await azureTableService.updateRequestStatus(request.partitionKey!, token, {
            status: 'Uploaded',
            blobUri: request.blobUri ? `${request.blobUri},${blobName}` : blobName
        });

        // Trigger Assemblyline scan
        assemblylineService.scanFile(request.partitionKey!, token, blobName);

        res.json({ message: 'Upload confirmed. Processing file.', status: 'Uploaded' });
    } catch (error) {
        res.status(500).json({ error: 'Internal server error' });
    }
};

export const closeRequest = async (req: Request, res: Response) => {
    try {
        const token = req.params.token as string;
        const request = await azureTableService.getRequestByTokenOnly(token);
        
        if (!request) return res.status(404).json({ error: 'Not found' });
        
        await azureTableService.updateRequestStatus(request.partitionKey!, token, {
            isClosed: true
        });

        res.json({ success: true });
    } catch (error) {
        res.status(500).json({ error: 'Internal server error' });
    }
};

export const listRequestorUploads = async (req: Request, res: Response) => {
    try {
        let requestorEmail = req.user?.preferred_username || (req.query.email as string) || 'admin@example.com';
        requestorEmail = requestorEmail.replace(/[\/\\#\?]/g, '_');
        
        const requests = await azureTableService.getRequestsByRequestor(requestorEmail);
        res.json(requests);
    } catch (error) {
        res.status(500).json({ error: 'Internal server error' });
    }
};

import crypto from 'crypto';

const generateSecret = (length: number = 32) => {
    // Generate a strong, URL-safe secret string of the requested length.
    // 24 random bytes => 32 base64url characters.
    return crypto.randomBytes(Math.ceil(length * 3 / 4)).toString('base64url').slice(0, length);
};

const generatePasscode = () => {
    return generateSecret(32);
};

const generateUploaderSecret = () => {
    return generateSecret(32);
};

export const uploadFileForSharing = async (req: Request, res: Response) => {
    try {
        let requestorEmail = req.user?.preferred_username || 'admin@example.com';
        requestorEmail = requestorEmail.replace(/[\/\\#\?]/g, '_');

        const { filename, expirationDays = 7, caseNumber } = req.body;
        
        if (!filename) {
            return res.status(400).json({ error: 'filename required' });
        }

        const token = uuidv4();
        const ext = filename.split('.').pop() || 'bin';
        const blobName = `${token}-${Date.now()}.${ext}`;

        // Create a share request record
        const entity = await azureTableService.createDownloadShare(
            requestorEmail,
            token,
            blobName,
            filename,
            parseInt(expirationDays),
            caseNumber
        );

        const sasInfo = azureBlobService.generateUploadSasToken(blobName);
        
        res.json({
            token,
            ...sasInfo,
            blobName,
            requestNumber: entity.requestNumber,
            caseNumber: entity.caseNumber
        });
    } catch (error: any) {
        console.error('Error creating share upload:', error.message);
        res.status(500).json({ error: 'Internal server error' });
    }
};

export const confirmShareUpload = async (req: Request, res: Response) => {
    try {
        let requestorEmail = req.user?.preferred_username || 'admin@example.com';
        requestorEmail = requestorEmail.replace(/[\/\\#\?]/g, '_');
        
        const { token, blobName, filename } = req.body;

        if (!token || !blobName) {
            return res.status(400).json({ error: 'token and blobName required' });
        }

        const share = await azureTableService.getDownloadShare(requestorEmail, token);
        if (!share) {
            return res.status(404).json({ error: 'Share not found' });
        }

        // Update share with confirmed blob
        await azureTableService.updateDownloadShare(requestorEmail, token, {
            blobUri: blobName,
            status: 'Ready',
            originalFilename: filename
        });

        res.json({ message: 'File uploaded successfully', token });
    } catch (error: any) {
        console.error('Error confirming share upload:', error.message);
        res.status(500).json({ error: 'Internal server error' });
    }
};

export const getDownloadShares = async (req: Request, res: Response) => {
    try {
        let requestorEmail = req.user?.preferred_username || 'admin@example.com';
        requestorEmail = requestorEmail.replace(/[\/\\#\?]/g, '_');

        const shares = await azureTableService.getDownloadSharesByRequestor(requestorEmail);
        res.json(shares);
    } catch (error: any) {
        console.error('Error fetching shares:', error.message);
        res.status(500).json({ error: 'Internal server error' });
    }
};

export const inviteDownloaderToShare = async (req: Request, res: Response) => {
    try {
        const token = req.params.token as string;
        const { downloaderEmail, expirationDays } = req.body;

        if (!downloaderEmail) {
            return res.status(400).json({ error: 'downloaderEmail required' });
        }

        let requestorEmail = req.user?.preferred_username || 'admin@example.com';
        requestorEmail = requestorEmail.replace(/[\/\\#\?]/g, '_');

        const share = await azureTableService.getDownloadShare(requestorEmail, token);
        if (!share) return res.status(404).json({ error: 'Share not found' });
        if (!share.blobUri) return res.status(400).json({ error: 'File not yet uploaded' });

        const downloadPasscode = generatePasscode();
        const downloadPasscodeHash = await bcrypt.hash(downloadPasscode, 10);

        await azureTableService.updateDownloadShare(requestorEmail, token, {
            downloaderEmail,
            downloadSecretHash: downloadPasscodeHash
        });

        const downloadLink = `${FRONTEND_URL}/download-share/${token}`;

        await gcNotifyService.sendDownloadRequestEmail(
            downloaderEmail,
            requestorEmail,
            downloadLink,
            downloadPasscode,
            share.requestNumber,
            share.caseNumber
        );

        res.status(200).json({ message: 'Downloader invitation email sent' });
    } catch (error: any) {
        console.error('Error inviting downloader to share:', error.message);
        res.status(500).json({ error: 'Internal server error' });
    }
};

export const validateShareDownloadSecret = async (req: Request, res: Response) => {
    try {
        const token = req.params.token as string;
        const { secret } = req.body;

        if (!secret) {
            return res.status(400).json({ error: 'Secret required' });
        }

        const share = await azureTableService.getDownloadShareByToken(token);
        if (!share) return res.status(404).json({ error: 'Not found or expired' });

        if (!share.downloadSecretHash) {
            return res.status(401).json({ error: 'Download not yet authorized' });
        }

        const isValid = await bcrypt.compare(secret, share.downloadSecretHash);
        if (!isValid) return res.status(401).json({ error: 'Invalid secret' });

        res.json({ success: true });
    } catch (error) {
        res.status(500).json({ error: 'Internal server error' });
    }
};

export const generateShareDownloadSas = async (req: Request, res: Response) => {
    try {
        const token = req.params.token as string;
        const secret = req.query.secret as string;

        if (!secret) return res.status(400).json({ error: 'Secret required' });

        const share = await azureTableService.getDownloadShareByToken(token);
        if (!share) return res.status(404).json({ error: 'Not found or expired' });

        if (!share.downloadSecretHash) {
            return res.status(401).json({ error: 'Download not yet authorized' });
        }

        const isValid = await bcrypt.compare(secret, share.downloadSecretHash);
        if (!isValid) return res.status(401).json({ error: 'Invalid secret' });

        if (!share.blobUri) return res.status(404).json({ error: 'File not available' });

        const sasUrl = azureBlobService.generateDownloadSasToken(share.blobUri);
        res.json({ url: sasUrl });
    } catch (error) {
        res.status(500).json({ error: 'Internal server error' });
    }
};

export const getShareInfo = async (req: Request, res: Response) => {
    try {
        const token = req.params.token as string;
        const share = await azureTableService.getDownloadShareByToken(token);
        
        if (!share || (share.expiresAt && new Date(share.expiresAt) < new Date())) {
            return res.status(404).json({ error: 'Share not found or expired.' });
        }

        res.json({
            originalFilename: share.originalFilename || 'file',
            status: share.status,
            hasDownloadSecret: !!share.downloadSecretHash,
            blobUri: share.blobUri || null,
            requestNumber: share.requestNumber,
            caseNumber: share.caseNumber
        });
    } catch (error) {
        res.status(500).json({ error: 'Internal server error' });
    }
};

export const inviteDownloader = async (req: Request, res: Response) => {
    try {
        const token = req.params.token as string;
        const { downloaderEmail, blobName, expirationDays } = req.body;

        if (!downloaderEmail) {
            return res.status(400).json({ error: 'downloaderEmail required' });
        }

        let requestorEmail = req.user?.preferred_username || 'admin@example.com';
        requestorEmail = requestorEmail.replace(/[\/\\#\?]/g, '_');

        const request = await azureTableService.getUploadRequest(requestorEmail, token);
        if (!request) return res.status(404).json({ error: 'Upload request not found' });
        if (!request.blobUri) return res.status(400).json({ error: 'No file has been uploaded yet' });

        // Determine which blob to share (use provided blobName or first one)
        const targetBlobName = blobName || request.blobUri.split(',')[0];
        
        // Verify the blob exists in the request
        if (!request.blobUri.includes(targetBlobName)) {
            return res.status(400).json({ error: 'Specified file not found in upload request' });
        }

        // Check if the specific file is clean before allowing sharing
        let fileStatus = request.status;
        if (request.fileStatuses) {
            try {
                const statuses = JSON.parse(request.fileStatuses);
                fileStatus = statuses[targetBlobName] || request.status;
            } catch (e) {
                // If parsing fails, use overall status
            }
        }
        
        if (fileStatus !== 'Clean') {
            return res.status(400).json({ error: 'File must be clean before sharing' });
        }

        // Create a new share record for tracking
        const shareToken = uuidv4();
        const originalFilename = targetBlobName.split('/').pop() || targetBlobName;

        // Use same expiration as original request or default to 7 days
        const originalExpirationDays = request.expiresAt ?
            Math.ceil((new Date(request.expiresAt).getTime() - Date.now()) / (1000 * 60 * 60 * 24)) : 7;
        const requestedExpirationDays = Number.isInteger(expirationDays) ? expirationDays : parseInt(expirationDays, 10);
        const effectiveExpirationDays = (Number.isInteger(requestedExpirationDays) && requestedExpirationDays > 0)
            ? requestedExpirationDays
            : Math.max(1, originalExpirationDays);

        const shareEntity = await azureTableService.createDownloadShare(
            requestorEmail,
            shareToken,
            targetBlobName,
            originalFilename,
            Math.max(1, effectiveExpirationDays),
            request.caseNumber || undefined,
            targetBlobName
        );

        // Update the share with downloader info and send invitation
        const downloadPasscode = generatePasscode();
        const downloadPasscodeHash = await bcrypt.hash(downloadPasscode, 10);

        await azureTableService.updateDownloadShare(requestorEmail, shareToken, {
            downloaderEmail,
            downloadSecretHash: downloadPasscodeHash,
            status: 'Awaiting Download'
        });

        const downloadLink = `${FRONTEND_URL}/download-share/${shareToken}`;

        await gcNotifyService.sendDownloadRequestEmail(
            downloaderEmail,
            requestorEmail,
            downloadLink,
            downloadPasscode,
            shareEntity.requestNumber,
            shareEntity.caseNumber
        );

        res.status(200).json({
            message: 'Downloader invitation email sent',
            shareToken,
            caseNumber: shareEntity.caseNumber
        });
    } catch (error: any) {
        console.error('Error sending downloader invite:', error.message, error.stack);
        res.status(500).json({ error: 'Internal server error' });
    }
};

export const validateDownloadSecret = async (req: Request, res: Response) => {
    try {
        const token = req.params.token as string;
        const { secret } = req.body;

        if (!secret) {
            return res.status(400).json({ error: 'Secret required' });
        }

        const request = await azureTableService.getRequestByTokenOnly(token);
        if (!request) return res.status(404).json({ error: 'Not found or expired' });

        if (!request.downloadSecretHash) {
            return res.status(401).json({ error: 'Download passcode not set' });
        }

        const isValid = await bcrypt.compare(secret, request.downloadSecretHash);
        if (!isValid) return res.status(401).json({ error: 'Invalid secret' });

        res.json({ success: true });
    } catch (error) {
        res.status(500).json({ error: 'Internal server error' });
    }
};

export const markDownloadComplete = async (req: Request, res: Response) => {
    try {
        const token = req.params.token as string;
        const { secret } = req.body;

        if (!secret) {
            return res.status(400).json({ error: 'Secret required' });
        }

        const request = await azureTableService.getRequestByTokenOnly(token);
        if (!request) return res.status(404).json({ error: 'Not found or expired' });

        if (!request.downloadSecretHash) {
            return res.status(401).json({ error: 'Download not authorized' });
        }

        const isValid = await bcrypt.compare(secret, request.downloadSecretHash);
        if (!isValid) return res.status(401).json({ error: 'Invalid secret' });

        // Update the request status to Downloaded
        await azureTableService.updateRequestStatus(request.partitionKey!, token, {
            status: 'Downloaded',
            downloadCompletedAt: new Date()
        });

        res.json({ success: true, message: 'Download marked as complete' });
    } catch (error) {
        res.status(500).json({ error: 'Internal server error' });
    }
};

export const markShareDownloadComplete = async (req: Request, res: Response) => {
    try {
        const token = req.params.token as string;
        const { secret } = req.body;

        if (!secret) {
            return res.status(400).json({ error: 'Secret required' });
        }

        const share = await azureTableService.getDownloadShareByToken(token);
        if (!share) return res.status(404).json({ error: 'Not found or expired' });

        if (!share.downloadSecretHash) {
            return res.status(401).json({ error: 'Download not authorized' });
        }

        const isValid = await bcrypt.compare(secret, share.downloadSecretHash);
        if (!isValid) return res.status(401).json({ error: 'Invalid secret' });

        // Update the share status to Downloaded
        await azureTableService.updateDownloadShare(share.partitionKey!, token, {
            status: 'Downloaded',
            downloadCompletedAt: new Date()
        });

        res.json({ success: true, message: 'Download marked as complete' });
    } catch (error) {
        res.status(500).json({ error: 'Internal server error' });
    }
}

export const generateDownloadSasForDownloader = async (req: Request, res: Response) => {
    try {
        const token = req.params.token as string;
        const filename = req.query.filename as string;
        const secret = req.query.secret as string;

        if (!secret) return res.status(400).json({ error: 'Secret required' });

        const request = await azureTableService.getRequestByTokenOnly(token);
        if (!request) return res.status(404).json({ error: 'Not found or expired' });

        if (!request.downloadSecretHash) {
            return res.status(401).json({ error: 'Download not yet authorized' });
        }

        const isValid = await bcrypt.compare(secret, request.downloadSecretHash);
        if (!isValid) return res.status(401).json({ error: 'Invalid secret' });

        if (!request.blobUri) return res.status(404).json({ error: 'No files available for download' });

        const targetBlob = filename || request.blobUri.split(',')[0];
        
        // Check if the specific file is malicious
        let fileStatus = request.status;
        if (request.fileStatuses) {
            try {
                const statuses = JSON.parse(request.fileStatuses);
                fileStatus = statuses[targetBlob] || request.status;
            } catch (e) {
                // If parsing fails, use overall status
            }
        }
        
        if (fileStatus === 'Malicious') {
            return res.status(403).json({ error: 'Download not allowed for malicious files.' });
        }

        const sasUrl = azureBlobService.generateDownloadSasToken(targetBlob);
        res.json({ url: sasUrl });
    } catch (error) {
        res.status(500).json({ error: 'Internal server error' });
    }
};

export const generateDownloadSas = async (req: Request, res: Response) => {
    try {
        const token = req.params.token as string;
        const filename = req.query.filename as string;
        let requestorEmail = req.user?.preferred_username || (req.query.email as string) || 'admin@example.com';
        requestorEmail = requestorEmail.replace(/[\/\\#\?]/g, '_');

        const request = await azureTableService.getUploadRequest(requestorEmail, token);
        
        if (!request) return res.status(404).json({ error: 'Not found or not authorized' });
        if (!request.blobUri) return res.status(404).json({ error: `No files uploaded.` });

        const targetBlob = filename || request.blobUri.split(',')[0];
        
        // Check if the specific file is clean before allowing download
        let fileStatus = request.status;
        if (request.fileStatuses) {
            try {
                const statuses = JSON.parse(request.fileStatuses);
                fileStatus = statuses[targetBlob] || request.status;
            } catch (e) {
                // If parsing fails, use overall status
            }
        }
        
        if (fileStatus !== 'Clean') {
            return res.status(403).json({ error: 'Download allowed only for clean files.' });
        }

        const sasUrl = azureBlobService.generateDownloadSasToken(targetBlob);
        res.json({ url: sasUrl });
    } catch (error) {
        res.status(500).json({ error: 'Internal server error' });
    }
};
