trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  node_version: '20.x' 

stages:
- stage: BuildAndPackage
  jobs:
  - job: BuildAndZip
    displayName: 'Build and Package App'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '$(node_version)'
      displayName: 'Install Node.js'

    - script: |
        cd backend
        npm install
        npm run build
      displayName: 'Build Backend'

    - script: |
        cd frontend
        npm install
        npm run build
      displayName: 'Build Frontend'

    - task: ArchiveFiles@2
      displayName: 'Archive Application files'
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/secure-file-portal.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish deployment artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/secure-file-portal.zip'
        ArtifactName: 'drop'
        publishLocation: 'Container'
