# Assemblyline 4 is composed of dozens of interconnected services, relying on multiple config files, policies, and environment variables.
# As such, it cannot be run from a single docker-compose file without compromising functionality and scale.
# The official installation instructions from CCCS are below:

# 1. First, ensure Docker has a larger address pool by making sure vm.max_map_count is increased:
#    sudo sysctl -w vm.max_map_count=262144

# 2. Clone the official CCCS docker-compose repository:
#    git clone https://github.com/CybercentreCanada/assemblyline-docker-compose.git al4-local
#    cd al4-local

# 3. Generate your self-signed certificate for the local UI HTTPS endpoints:
#    openssl req -nodes -x509 -newkey rsa:4096 -keyout config/nginx.key -out config/nginx.crt -days 365 -subj "/C=CA/ST=Ontario/L=Ottawa/O=CCCS/CN=assemblyline.local"

# 4. Pull all images:
#    docker compose pull --ignore-buildable
#    docker compose -f bootstrap-compose.yaml pull

# 5. Build necessary dependent containers:
#    env COMPOSE_BAKE=true docker compose build

# 6. Bring the core components online (detached):
#    docker compose up -d --wait

# 7. Bring up the bootstrap instance that seeds Kibana and Elasticsearch:
#    docker compose -f bootstrap-compose.yaml up

# Access the UI using default credentials at https://localhost
# Ensure you update the API variables in this proxy (.env) with the AssemblyLine4 endpoint:
# ASSEMBLYLINE_URL=https://localhost
